export const PRODUCTS_OF_CATEGORY_LOADING = "PRODUCTS_OF_CATEGORY_LOADING";
export const PRODUCTS_OF_CATEGORY_SUCCESS = "PRODUCTS_OF_CATEGORY_SUCCESS";
export const PRODUCTS_OF_CATEGORY_FAIL = "PRODUCTS_OF_CATEGORY_FAIL";