export const GET_PRODUCTS_LOADING="GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL";
export const FETCH_PRODUCTS="FETCH_PRODUCTS";
export const SET_PRODUCTS_EMPTY="SET_PRODUCTS_EMPTY";