export const GET_BRANDS_LOADING="GET_BRANDS_LOADING";
export const GET_BRANDS_SUCCESS="GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAIL="GET_BRANDS_FAIL";
export const FETCH_BRANDS="FETCH_BRANDS";
export const SET_BRANDS_EMPTY="SET_BRANDS_EMPTY";
