// <auto-generated />
using System;
using BOL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BOL.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20220313070734_create-product-category-brand")]
    partial class createproductcategorybrand
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BOL.Entities.Brand", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)");

                    b.Property<DateTime>("CreatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<string>("FullDescription")
                        .IsUnicode(true)
                        .HasColumnType("ntext");

                    b.Property<bool>("IsActive")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Order")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("BOL.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)");

                    b.Property<DateTime>("CreatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<string>("FullDescription")
                        .IsUnicode(true)
                        .HasColumnType("ntext");

                    b.Property<bool>("IsActive")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Order")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("BOL.Entities.Category_Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("char(12)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("char(12)");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Category_Product");
                });

            modelBuilder.Entity("BOL.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)");

                    b.Property<DateTime>("CreatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<string>("FullDescription")
                        .IsUnicode(true)
                        .HasColumnType("ntext");

                    b.Property<bool>("IsActive")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasPrecision(18, 2)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceDiscount")
                        .HasPrecision(18, 2)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsUnicode(false)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BOL.Entities.Category_Product", b =>
                {
                    b.HasOne("BOL.Entities.Category", "Category")
                        .WithMany("Category_Product")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BOL.Entities.Product", "Product")
                        .WithMany("Category_Products")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BOL.Entities.Product", b =>
                {
                    b.HasOne("BOL.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("BOL.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BOL.Entities.Category", b =>
                {
                    b.Navigation("Category_Product");
                });

            modelBuilder.Entity("BOL.Entities.Product", b =>
                {
                    b.Navigation("Category_Products");
                });
#pragma warning restore 612, 618
        }
    }
}
